### ISSUE TITLE
webpack -w (--watch) +file-loader でうまくいかないケース

### ISSUE THREAD

**Issue by takeyuweb** [takeyuweb/rails-webpack-sample#5]
```scss
body {
    background: url("../images/stripe.png");
}
```

↓

```scss
body {
    background: #000;
}
```

いったん `public/bundle/images/stripe.png` が消えて

↓

```scss
body {
    background: url("../images/stripe.png");
}
```

ここでまた必要になるけど、 `public/bundle/images/stripe.png` が復活しない。

いったん `webpack -w` を終了してやり直す必要がある。
